# Generated by Django 3.2.8 on 2021-10-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort', to='Trackerapp.devstyle'),
        ),
    ]
