# Generated by Django 3.2.8 on 2021-10-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('details', models.CharField(blank=True, default='A Moringa class.', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trackerapp.cohort'),
        ),
    ]
