# Generated by Django 3.2.8 on 2021-10-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0002_cohort_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cohort',
        ),
    ]
