# Generated by Django 3.2.8 on 2021-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0002_auto_20211006_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='code',
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.CharField(default='A programming language/framework.', max_length=100, null=True),
        ),
    ]
