# Generated by Django 3.2.8 on 2021-10-14 13:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0003_auto_20211014_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='second_name',
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='full_name', unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
