# Generated by Django 3.2.8 on 2021-10-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0003_remove_project_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='Trackerapp.cohort'),
        ),
    ]
