# Generated by Django 3.2.8 on 2021-10-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0004_project_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='Trackerapp.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_project', to='Trackerapp.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum', to='Trackerapp.student'),
        ),
    ]
