# Generated by Django 3.2.8 on 2021-10-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0005_auto_20211008_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_member', to='Trackerapp.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_scrum', to='Trackerapp.student'),
        ),
    ]
