# Generated by Django 3.2.8 on 2021-10-14 13:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0005_remove_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='full_name', unique=True),
        ),
    ]
