# Generated by Django 3.2.8 on 2021-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0006_auto_20211008_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_member', to='Trackerapp.Student'),
        ),
    ]
