# Generated by Django 3.2.8 on 2021-10-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0006_student_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
