# Generated by Django 3.2.8 on 2021-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0007_auto_20211008_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
