# Generated by Django 3.2.8 on 2021-10-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0008_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
