# Generated by Django 3.2.8 on 2021-10-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0008_auto_20211017_2153'),
        ('Trackerapp', '0008_auto_20211017_2156'),
    ]

    operations = [
    ]
