# Generated by Django 3.2.8 on 2021-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0009_remove_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='is_member', to='Trackerapp.Student'),
        ),
    ]
