# Generated by Django 3.2.8 on 2021-10-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0010_alter_project_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='style',
        ),
        migrations.AlterField(
            model_name='devstyle',
            name='description',
            field=models.CharField(default='A programming language/style.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to='Trackerapp.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_owned', to='Trackerapp.student'),
        ),
    ]
