# Generated by Django 3.2.8 on 2021-10-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0008_auto_20211017_2325'),
        ('Trackerapp', '0010_auto_20211019_1133'),
    ]

    operations = [
    ]
