# Generated by Django 3.2.8 on 2021-10-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0008_auto_20211017_2325'),
        ('Trackerapp', '0009_remove_customuser_is_verified'),
        ('Trackerapp', '0011_remove_customuser_is_verified'),
    ]

    operations = [
    ]
