# Generated by Django 3.2.8 on 2021-10-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0011_auto_20211011_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='is_dev', to='Trackerapp.Student'),
        ),
    ]
