# Generated by Django 3.2.8 on 2021-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0012_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
