# Generated by Django 3.2.8 on 2021-10-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0012_alter_project_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='member',
            new_name='members',
        ),
    ]
