# Generated by Django 3.2.8 on 2021-10-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0013_student_github_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scrum',
        ),
    ]
